import { Inter } from "next/font/google";

import "@/assets/css/global-min.css";
import "@/assets/css/cb82.css";
import "@/assets/css/with-flex.css";
import "@/assets/css/home-with-flex.css";
import "@/assets/css/fonts.css";
import "@/assets/css/additional.css";
import "@/assets/css/override.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html className="touch" lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://irp.cdn-website.com/fonts/css2?family=Barlow:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&amp;family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&amp;family=Montserrat:ital,wght@0,100..900;1,100..900&amp;family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&amp;family=Oswald:ital,wght@0,200..700;1,200..700&amp;family=Source+Sans+Pro:ital,wght@0,200;0,300;0,400;0,600;0,700;0,900;1,200;1,300;1,400;1,600;1,700;1,900&amp;subset=latin-ext&amp;display=swap"
          as="style"
          fetchPriority="low"
          type="text/css"
        />

        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css"
          integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg=="
          crossOrigin="anonymous"
          referrerPolicy="no-referrer"
        />
      </head>
      <body
        id="dmRoot"
        data-page-alias="home"
        className="dmRoot dmMobileBody fix-mobile-scrolling addCanvasBorder dmResellerSite pcCustomScrollbar d1SiteBody dmLayoutBody dmBodyNoIscroll"
        style={{ padding: 0, margin: 0 }}
      >
        {children}
      </body>
    </html>
  );
}
